version: '3.8'

services:
  app:
    build: .
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "9098:9098"

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    restart: always
