version: '3.8'

services:
  server: 
    build: .
    depends_on:
      - redis
    environment:
      DATABASE_URL: $DATABASE_URL
      ACCESS_TOKEN_SECRET: $ACCESS_TOKEN_SECRET
      RENEW_TOKEN_SECRET: $RENEW_TOKEN_SECRET
    ports:
      - "9098:9098"

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    restart: always
  
  database:
    image: postgres:17.4
    restart: always
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
    ports:
      - "5432:5432"
    labels:
      com.swc.kind: "db"

