services:
  dev-redis:
    image: redis:7
    container_name: dev-feft-redis
    ports:
      - "9001:6379"
    restart: always
    volumes:
      - ./volumes/dev/redis:/data

  
  dev-database:
    image: postgres:17.4
    restart: always
    container_name: dev-feft-db
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
    ports:
      - "9000:5432"
    volumes:
      - ./volumes/dev/db:/var/lib/postgresql/data

  dev-server: 
    image: feft-server:latest
    build: .
    container_name: dev-feft-server
    depends_on:
      - dev-redis
      - dev-database
    environment:
      DATABASE_URL: $DATABASE_URL
      REDIS_URL: $REDIS_URL
      ACCESS_TOKEN_SECRET: $ACCESS_TOKEN_SECRET
      RENEW_TOKEN_SECRET: $RENEW_TOKEN_SECRET
    ports:
      - "8080:9098"
