services:
  prod-redis:
    image: redis:7
    container_name: prod-feft-redis
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - ./volumes/prod/redis:/data

  
  prod-database:
    image: postgres:17.4
    restart: always
    container_name: prod-feft-db
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/prod/db:/var/lib/postgresql/data

  prod-server: 
    image: feft-server:latest
    build: .
    container_name: prod-feft-server
    depends_on:
      - prod-redis
      - prod-database
    environment:
      DATABASE_URL: $DATABASE_URL
      REDIS_URL: $REDIS_URL
      ACCESS_TOKEN_SECRET: $ACCESS_TOKEN_SECRET
      RENEW_TOKEN_SECRET: $RENEW_TOKEN_SECRET
    ports:
      - "9098:9098"
